if (!require(devtools)) install.packages("devtools")
library(devtools)
devtools::install_github("r-lib/devtools")
if (!requireNamespace("remotes"))
install.packages("remotes")
remotes::install_github("rstudio/renv")
# -----------------------------------------------------------------------------
setwd("~/GitHub/retailer_pre_earnings")
renv::init(bare = TRUE)
renv::status()
renv::snapshot()
devtools::install_github("r-lib/devtools")
renv::snapshot()
remotes::install_github("ManuelHentschel/vscDebugger")
install.packages('jsonlite', dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
options(repos = c(RSM = "https://radiant-rstats.github.io/minicran", CRAN = "https://cloud.r-project.org"))
install.packages("radiant.update")
remotes::install_github("REditorSupport/languageserver", force = TRUE)
install.packages("data.table")
update.packages()
library(data.table)                   # attach it
folder_root             <- "C:/Users/glen.falk/OneDrive - IHS Markit/Documents"
folder_github           <- "/github"
folder_new              <- c("/cheatsheet/", "/dashboard/", "/rds/")
folder_project_template <- paste0(folder_root,folder_github, "/ProjectTemplate")
folder_target           <- getwd()
folder_project_template <- paste0(folder_root,folder_github, "/volume")
folder_source           <- folder_project_template
dt_source               <- data.table::as.data.table(folder_source)
dt_target               <- data.table::as.data.table(folder_target)
sub_folder              <- c("/config/",
"/data/",
"/docs/",
"/lib/",
"/munge/",
"/reports")
dt_folder_new           <- data.table::as.data.table(matrix(folder_new))
dt_subfolder            <- data.table::as.data.table(matrix(sub_folder))
# -----------------------------------------------------------------------------
dt_folder_new           <- dt_target[,as.list(dt_folder_new), by = dt_target]
# -----------------------------------------------------------------------------
dt_folder_copy_from     <- dt_source[,as.list(dt_subfolder), by = dt_source]
dt_folder_copy_from     <- dt_folder_copy_from[,path_from:= paste0(folder_source,V1)][,3]
dt_folder_copy_to       <- dt_target[,as.list(dt_subfolder), by=dt_target]
dt_folder_new           <- dt_folder_new[,path:= paste0(folder_target,V1)][,3]
dt_folder_copy_to       <- dt_folder_copy_to[,path_to:= paste0(folder_target,V1)][,3]
# -----------------------------------------------------------------------------
dt_folder_copy          <- cbind.data.frame(dt_folder_copy_from, dt_folder_copy_to)
mapply(dir.create, paths = dt_folder_new[,1], showWarnings = TRUE,
recursive = FALSE, mode = "0777")
# -----------------------------------------------------------------------------
mapply(file.copy, from=dt_folder_copy[,1], to=dt_target,
overwrite = TRUE, recursive = TRUE)
install.packages("tableHTML")
renv::snapshot()
devtools::install_github("bergant/datamodelr")
devtools::install_github("bergant/finstr")
devtools::install_github("b-rodrigues/loud")
devtools::install_github("btskinner/rscorecard")
devtools::install_github("dreamRs/shinyWidgets")
devtools::install_github("emilopezcano/SixSigma")
devtools::install_github("gadenbuie/grkstyle")
devtools::install_github("gadenbuie/rsthemes")
devtools::install_github("gagolews/stringi")
devtools::install_github("gavinrozzi/zipcodeR")
devtools::install_github("hzambran/hydroTSM")
devtools::install_github("haozhu233/kableExtra")
devtools::install_github("patzaw/ReDaMoR")
devtools::install_github("renkun-ken/formattable")
devtools::install_github(c("ramnathv/htmlwidgets", "rstudio/dygraphs"))
devtools::install_github("R-Finance/blotter")
devtools::install_github("r-lib/cli")
devtools::install_github("r-lib/httr")
devtools::install_github("r-lib/keyring")
devtools::install_github("r-lib/usethis")
devtools::install_github("smach/rmiscutils")
devtools::install_github("ropensci/plotly")
devtools::install_github("rstudio/gt")
devtools::install_github("sfirke/janitor")
devtools::install_github("statisticsNZ/simplevis")
devtools::install_github("Swechhya/excelR")
devtools::install_github("talgalili/d3heatmap")
devtools::install_github("talgalili/heatmaply")
devtools::install_github("tidyverse/tidyverse")
devtools::install_github("timelyportfolio/sunburstR")
devtools::install_github("yihui/formatR")
usethis::create_github_token()
usethis::edit_r_environ()
gitcreds::gitcreds_set()
renv::status()
renv::snapshot()
devtools::install_github("talgalili/heatmaply")
devtools::install_github("tidyverse/tidyverse")
devtools::install_github("timelyportfolio/sunburstR")
devtools::install_github("yihui/formatR")
install.packages('curl', repos = 'http://cran.r-project.org', Ncpus = 6)
install.packages( c("billboarder", "beepr", "cheatsheet,", "checkpoint", "DataExplorer", "plotluck", "poorman", "rmiscutils"), Ncpus = 6)
renv::status()
install.packages( c("newsmap", "seededlda", "spacyr"), Ncpus = 6)
devtools::install_github('daattali/addinslist')
devtools::install_github("BAAQMD/copydat")
devtools::install_github("ChrisDienes/SeaClass")
devtools::install_github("LudvigOlsen/insertImage")
devtools::install_github("LudvigOlsen/splitChunk")
devtools::install_github("MilesMcBain/datapasta")
devtools::install_github("RhoInc/CRANsearcher")
devtools::install_github("Stan125/GREA")
devtools::install_github("Stan125/limoaddin")
devtools::install_github("ThinkR-open/littleboxes")
devtools::install_github("YvesCR/arimaUI")
devtools::install_github("alan-y/objectremover")
devtools::install_github("benmarwick/snakecaser")
devtools::install_github("benmarwick/wordcountaddin", type = "source", dependencies = TRUE)
devtools::install_github("bnosac/taskscheduleR")
devtools::install_github("calligross/ggthemeassist")
devtools::install_github("crsh/citr")
devtools::install_github("csgillespie/addinmanager")
devtools::install_github("daattali/addinslist")
devtools::install_github("daattali/ggExtra")
devtools::install_github("daranzolin/ViewPipeSteps")
devtools::install_github("daranzolin/compareAreas")
devtools::install_github("daranzolin/typeStringsGadget")
devtools::install_github("dkilfoyle/rpivotGadget")
devtools::install_github("dokato/todor")
devtools::install_github("donlelef/tsviz")
devtools::install_github("dracodoc/mischelper")
devtools::install_github("dracodoc/namebrowser")
devtools::install_github("dreamRs/addinit")
devtools::install_github("dreamRs/viewxl")
devtools::install_github("erictleung/unnestIfElse")
devtools::install_github("fkeck/quickview")
devtools::install_github("flaviobarros/shinyExams")
devtools::install_github("gadenbuie/ermoji")
devtools::install_github("haozhu233/giphyr")
devtools::install_github("homerhanumat/addinplots")
devtools::install_github("jeffjjohnston/RStudioConsoleRender")
devtools::install_github("jennybc/jadd")
devtools::install_github("kieranjmartin/viewenhance")
devtools::install_github("lbusett/insert_table")
devtools::install_github("lorenzwalthert/strcode")
devtools::install_github("milesmcbain/mufflr")
devtools::install_github("mlysy/rdoxygen")
devtools::install_github("mrjoh3/mapedit.addin")
devtools::install_github("mvkorpel/uniscape")
devtools::install_github("mwip/beautifyR")
devtools::install_github("nevrome/wellspell.addin")
devtools::install_github("petermeissner/assignparams")
devtools::install_github("r-hub/pkgsearch")
devtools::install_github("sarupurisailalith/commonUtilAddins")
devtools::install_github("seasmith/AlignAssign")
devtools::install_github("sfr/RStudio-Addin-Snippets")
devtools::install_github("strboul/caseconverter")
devtools::install_github("tjmahr/WrapRmd")
devtools::install_github('Timag/imageclipr')
devtools::install_github('dcomtois/sortLines')
devtools::install_github('n8thangreen/jagsAddIn')
devtools::install_github('paulgovan/QRAGadget')
devtools::install_github('xiaoa6435/RmdImgPaste')
devtools::install_github("quanteda/quanteda.corpora")
devtools::install_github("omegahat/RDCOMClient")
devtools::install_github("mkuhn/dict")
install_github("quandl/quandl-r")
install.packages("remotes")  # if not yet installed
remotes::install_github("matt-dray/blogsnip")
remotes::install_github("R-CoderDotCom/ggdogs@main")
remotes::install_github("arcruz0/inexact")
remotes::install_github('jorvlan/raincloudplots')
remotes::install_github('yihui/xaringan')
renv::snapshot()
savehistory("~/github/retailer_pre_earnings/docs/projec_setup.Rhistory")
install.packages("xgboost")
install.packages(c("admisc", "berryFunctions", "blob", "bookdown", "broom", "broom.mixed", "caret", "cli", "cluster", "colorspace", "commonmark", "conquer", "correlation", "datawizard", "DEoptimR", "deSolve", "DiagrammeR", "dlookr", "dm", "dplyr", "emmeans", "extrafont", "fansi", "flextable", "foreach", "formatR", "future", "gdtools", "geojsonsf", "gert", "ggExtra", "ggfun", "ggiraph", "ggpp", "gifski", "glmnet", "glue", "gower", "GPArotation", "grafify", "gt", "haven", "httpgd", "igraph", "insight", "iterators", "jsonlite", "lavaan", "leafem", "leaflet", "lme4", "lmtest", "magrittr", "maptools", "MASS", "MatchIt", "Matrix", "MCMCpack", "mgcv", "modelsummary", "nlme", "officer", "openssl", "pagedown", "pander", "parallelly", "parameters", "performance", "phosphoricons", "pkgcache", "pkgdepends", "plyr", "polynom", "processx", "psych", "quantreg", "randomForest", "RColorBrewer", "Rcpp", "RcppArmadillo", "RcppEigen", "RCurl", "readxl", "recipes", "ReDaMoR", "reshape", "rgdal", "robustbase", "rrtable", "rscorecard", "RSQLite", "Rttf2pt1", "sass", "scales", "sf", "shinybusy", "shinyWidgets", "showtext", "simplevis", "sjlabelled", "stargazer", "statsExpressions", "styler", "survival", "svglite", "sysfonts", "systemfonts", "taskscheduleR", "terra", "testthat", "tidycensus", "tidyselect", "tigris", "timetk", "tseries", "tzdb", "units", "uuid", "V8", "vctrs", "venneuler", "VGAM", "webshot", "xfun", "xgboost", "XML", "yaml", "zoo"), lib="C:/Users/glen.falk/OneDrive - IHS Markit/Documents/R/R-4.1.2/library")
savehistory("~/github/retailer_pre_earnings/docs/project_setup.r")
savehistory("~/github/ProjectTemplate/history/project_setup.Rhistory")
savehistory("~/github/ProjectTemplate/docs/project_setup.r")
